version: '3'
services:
    as_workNode_0_EngineeringHub_ParallelExample:
        #linkedComponent:HostNameTest
        #imageHash:4dc83cedcfefadfa47c17708b364ec307d849a5e7b807609ff7bf012000c53cb
        restart: on-failure
        image: '10.10.9.84:5000/as:3.0'
        hostname: 'as_workNode_0_EngineeringHub_ParallelExample'
        volumes:
            - C:\Users\Will Keel\Desktop\EngineeringHub_JPLDemo\Analyses:C:\Users\ContainerAdministrator\AppData\Roaming\Phoenix Integration\AServer13.1\analyses
        command: "C:/Program Files/Phoenix Integration/Analysis Server 13.1/aserver.exe"
    as_workNode_1_EngineeringHub_ParallelExample:
        #linkedComponent:HostNameTest
        #imageHash:4dc83cedcfefadfa47c17708b364ec307d849a5e7b807609ff7bf012000c53cb
        restart: on-failure
        image: '10.10.9.84:5000/as:3.0'
        hostname: 'as_workNode_1_EngineeringHub_ParallelExample'
        volumes:
            - C:\Users\Will Keel\Desktop\EngineeringHub_JPLDemo\Analyses:C:\Users\ContainerAdministrator\AppData\Roaming\Phoenix Integration\AServer13.1\analyses
        command: "C:/Program Files/Phoenix Integration/Analysis Server 13.1/aserver.exe"
    as_headNode_EngineeringHub_ParallelExample:
        #linkedComponent:HostNameTest
        #imageHash:4dc83cedcfefadfa47c17708b364ec307d849a5e7b807609ff7bf012000c53cb
        restart: on-failure
        image: '10.10.9.84:5000/as:3.0'
        hostname: 'as_headNode_EngineeringHub_ParallelExample'
        volumes:
            - C:\Users\Will Keel\Desktop\EngineeringHub_JPLDemo\Analyses:C:\Users\ContainerAdministrator\AppData\Roaming\Phoenix Integration\AServer13.1\analyses
        command: "C:/Program Files/Phoenix Integration/Analysis Server 13.1/aserver.exe"
